defaults:
  - _self_                     # <-- configs defined in this yaml. They are overwritten by all following defaults
  - model: cifar_resnet.yaml
  - dataset: streaming_cifar10.yaml
  - logger: null
  - optimizer: default.yaml
  - scheduler: default.yaml
  - callbacks:
    - lr_monitor.yaml
    - speed_monitor.yaml
    - checkpoint.yaml
  - trainer: default.yaml
  - algorithms: null
  - experiment: null
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: sphere
    storage: null
    n_trials: 10
    n_jobs: 1
    params:
      optimizer.lr: range(0.01, 0.1, step=0.01)

seed: 42
name: karan-hydra-test-run