# @package _global_

defaults:
  - _self_                     # <-- configs defined in this yaml. They are overwritten by all following defaults
  - model: cifar_resnet.yaml
  - dataset: streaming_cifar10.yaml
  - logger: wandb.yaml
  - optimizer: default.yaml
  - scheduler: default.yaml
  - callbacks:  
    - lr_monitor.yaml
    - speed_monitor.yaml
    - checkpoint.yaml
  - trainer: default.yaml
  - algorithms: null 
  - experiment: null

hydra:
  sweeper:
    params:
      seed: 42, 43, 44
      name: karan-hydra-test-run-42, karan-hydra-test-run-43, karan-hydra-test-run-44





