# @package _global_

defaults:
  - _self_                     # <-- configs defined in this yaml. They are overwritten by all following defaults
  - model: cifar_resnet.yaml
  - dataset: streaming_cifar10.yaml
  - logger: wandb.yaml
  - optimizer: default.yaml
  - scheduler: default.yaml
  - callbacks:  
    - lr_monitor.yaml
    - speed_monitor.yaml
    - checkpoint.yaml
  - trainer: default.yaml
  - algorithms: null 
  - experiment: null

seed: 42
name: karan-hydra-test-run

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    params:
      optimizers.lr: tag(log, interval(0.00001, 0.01))





